DECLARE @ACUMULADO INT

SELECT  
        ROW_NUMBER()OVER(ORDER BY MERCADO) NUMERO
       ,REG_BI
       ,MERCADO
       ,NOMBRE
       ,SUMA
       ,SUM(SUMA)OVER(PARTITION BY MERCADO ORDER BY MERCADO DESC) AS TOTAL_REGION
       ,((SUM(SUMA)OVER(PARTITION BY REG_BI ORDER BY REG_BI DESC))/5) AS DIV

       --INTO TOTAL#
       --,@ACUMULADO=@ACUMULADO
       --,IIF(@ACUMULADO>0,'POSITIVO','N')
        --INTO ACUMULADO#
FROM [dbo].[MEDICOS_CAT] 

--WHERE ACUMULADO BETWEEN 1150 1782 AND 20;

ORDER BY SUMA DESC
