SELECT 

      
      [PERIODO]
      ,[COD_BI]
      ,[NOM_BI]
      ,[MDO_RVTE]
      ,[PRODUCTO]
      ,[SUMA]
       ,ROW_NUMBER()OVER(PARTITION  BY PERIODO,COD_BI,NOM_BI,MDO_RVTE ORDER BY PERIODO,COD_BI,NOM_BI,MDO_RVTE, SUMA DESC ) RK
  FROM [BD_LUMINOVA].[dbo].[MEDICOS_MARCA#]